import { ContactType, ScheduledType } from "redux/types";

export interface ScheduleServiceType {
  createSchedule?: any;
  getSchedule?: any;
  getContactSchedule?: any;
  createMessageSchedule?: any;
  deleteSchedule?: any;
}

export interface CreateScheduleType {
  name: string;
  contact_group_id: number;
  scheduledDate:string;
}

export interface CreateMessageScheduleType {
  text: string;
  autoGenerated: string | null;
  chat_id?: number;
  scheduler_id: number;
  subject: string;
  transporter: string;
}

export interface ContactScheduleType {
  id: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  contact: ContactType;
  schedule: ScheduledType;
}